services:
  autolog:
    build: .
    container_name: autolog
    restart: unless-stopped
    env_file:
      - path: .env
    environment:
      - STORE_PATH=/data/autolog.db
    volumes:
      - autolog-data:/data
    networks:
      - dokploy-network

volumes:
  autolog-data:

networks:
  dokploy-network:
    external: true
